# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1236, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 271, 711))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.pbt_scanSerialPort = QtWidgets.QPushButton(self.groupBox)
        self.pbt_scanSerialPort.setObjectName("pbt_scanSerialPort")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pbt_scanSerialPort)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBox_baudrate = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_baudrate.setMinimum(9600)
        self.spinBox_baudrate.setMaximum(4000000)
        self.spinBox_baudrate.setSingleStep(100)
        self.spinBox_baudrate.setProperty("value", 1000000)
        self.spinBox_baudrate.setObjectName("spinBox_baudrate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_baudrate)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pbt_serialOpen = QtWidgets.QPushButton(self.groupBox)
        self.pbt_serialOpen.setObjectName("pbt_serialOpen")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.pbt_serialOpen)
        self.combox_serialPortList = QtWidgets.QComboBox(self.groupBox)
        self.combox_serialPortList.setObjectName("combox_serialPortList")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.combox_serialPortList)
        self.verticalLayout.addWidget(self.groupBox)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spinBox_displayCol = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_displayCol.setMinimum(8)
        self.spinBox_displayCol.setMaximum(480)
        self.spinBox_displayCol.setSingleStep(8)
        self.spinBox_displayCol.setProperty("value", 128)
        self.spinBox_displayCol.setObjectName("spinBox_displayCol")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_displayCol)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_displayRow = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_displayRow.setMinimum(8)
        self.spinBox_displayRow.setMaximum(480)
        self.spinBox_displayRow.setSingleStep(8)
        self.spinBox_displayRow.setProperty("value", 64)
        self.spinBox_displayRow.setObjectName("spinBox_displayRow")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_displayRow)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_displayScanDirection = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_displayScanDirection.setObjectName("comboBox_displayScanDirection")
        self.comboBox_displayScanDirection.addItem("")
        self.comboBox_displayScanDirection.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_displayScanDirection)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_displayByteDirection = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_displayByteDirection.setObjectName("comboBox_displayByteDirection")
        self.comboBox_displayByteDirection.addItem("")
        self.comboBox_displayByteDirection.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_displayByteDirection)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_displaySignBit = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_displaySignBit.setObjectName("comboBox_displaySignBit")
        self.comboBox_displaySignBit.addItem("")
        self.comboBox_displaySignBit.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_displaySignBit)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.checkBox_displayFlipH = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_displayFlipH.setObjectName("checkBox_displayFlipH")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_displayFlipH)
        self.checkBox_displayFlipV = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_displayFlipV.setObjectName("checkBox_displayFlipV")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_displayFlipV)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_18 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_18.setObjectName("groupBox_18")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_18)
        self.formLayout_7.setObjectName("formLayout_7")
        self.radioButton_binarizationThreshold = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_binarizationThreshold.setEnabled(True)
        self.radioButton_binarizationThreshold.setChecked(True)
        self.radioButton_binarizationThreshold.setObjectName("radioButton_binarizationThreshold")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_binarizationThreshold)
        self.radioButton_binarizationDither = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_binarizationDither.setObjectName("radioButton_binarizationDither")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_binarizationDither)
        self.comboBox_ditherBayerSize = QtWidgets.QComboBox(self.groupBox_18)
        self.comboBox_ditherBayerSize.setObjectName("comboBox_ditherBayerSize")
        self.comboBox_ditherBayerSize.addItem("")
        self.comboBox_ditherBayerSize.addItem("")
        self.comboBox_ditherBayerSize.addItem("")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_ditherBayerSize)
        self.radioButton_binarizationErrorDiffusion = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_binarizationErrorDiffusion.setObjectName("radioButton_binarizationErrorDiffusion")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioButton_binarizationErrorDiffusion)
        self.checkBox_binarizationEqualizeHist = QtWidgets.QCheckBox(self.groupBox_18)
        self.checkBox_binarizationEqualizeHist.setObjectName("checkBox_binarizationEqualizeHist")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_binarizationEqualizeHist)
        self.verticalLayout.addWidget(self.groupBox_18)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(300, 10, 931, 711))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 231, 561))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbt_openImageFile = QtWidgets.QPushButton(self.groupBox_3)
        self.pbt_openImageFile.setObjectName("pbt_openImageFile")
        self.verticalLayout_3.addWidget(self.pbt_openImageFile)
        self.lineEdit_imageFileName = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_imageFileName.setObjectName("lineEdit_imageFileName")
        self.verticalLayout_3.addWidget(self.lineEdit_imageFileName)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_previewRaw = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_previewRaw.setChecked(True)
        self.radioButton_previewRaw.setObjectName("radioButton_previewRaw")
        self.verticalLayout_4.addWidget(self.radioButton_previewRaw)
        self.radioButton_previewGray = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_previewGray.setObjectName("radioButton_previewGray")
        self.verticalLayout_4.addWidget(self.radioButton_previewGray)
        self.radioButton_previewBW = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_previewBW.setObjectName("radioButton_previewBW")
        self.verticalLayout_4.addWidget(self.radioButton_previewBW)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox_BWThreshold = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_BWThreshold.setMinimum(1)
        self.spinBox_BWThreshold.setMaximum(254)
        self.spinBox_BWThreshold.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_BWThreshold.setProperty("value", 127)
        self.spinBox_BWThreshold.setDisplayIntegerBase(10)
        self.spinBox_BWThreshold.setObjectName("spinBox_BWThreshold")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_BWThreshold)
        self.horizontalSlider_BWThreshold = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_BWThreshold.setMinimum(1)
        self.horizontalSlider_BWThreshold.setMaximum(254)
        self.horizontalSlider_BWThreshold.setProperty("value", 127)
        self.horizontalSlider_BWThreshold.setTracking(True)
        self.horizontalSlider_BWThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BWThreshold.setInvertedAppearance(False)
        self.horizontalSlider_BWThreshold.setInvertedControls(False)
        self.horizontalSlider_BWThreshold.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_BWThreshold.setTickInterval(10)
        self.horizontalSlider_BWThreshold.setObjectName("horizontalSlider_BWThreshold")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalSlider_BWThreshold)
        self.checkBox_BWInvert = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_BWInvert.setObjectName("checkBox_BWInvert")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_BWInvert)
        self.checkBox_previewBW2x = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_previewBW2x.setChecked(True)
        self.checkBox_previewBW2x.setObjectName("checkBox_previewBW2x")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_previewBW2x)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_exportHexCArray = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_exportHexCArray.setChecked(True)
        self.radioButton_exportHexCArray.setObjectName("radioButton_exportHexCArray")
        self.verticalLayout_5.addWidget(self.radioButton_exportHexCArray)
        self.radioButton_exportHexValue = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_exportHexValue.setObjectName("radioButton_exportHexValue")
        self.verticalLayout_5.addWidget(self.radioButton_exportHexValue)
        self.pbt_exportImage = QtWidgets.QPushButton(self.groupBox_6)
        self.pbt_exportImage.setObjectName("pbt_exportImage")
        self.verticalLayout_5.addWidget(self.pbt_exportImage)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(250, 390, 641, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_8)
        self.widget_5.setGeometry(QtCore.QRect(10, 20, 371, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_previewOutputBW = QtWidgets.QLabel(self.widget_5)
        self.label_previewOutputBW.setFrameShape(QtWidgets.QFrame.Box)
        self.label_previewOutputBW.setText("")
        self.label_previewOutputBW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_previewOutputBW.setObjectName("label_previewOutputBW")
        self.gridLayout.addWidget(self.label_previewOutputBW, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.groupBox_8)
        self.widget_6.setGeometry(QtCore.QRect(390, 20, 231, 231))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_SendImageAuto = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_SendImageAuto.setObjectName("radioButton_SendImageAuto")
        self.verticalLayout_9.addWidget(self.radioButton_SendImageAuto)
        self.radioButton_sendImageManually = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_sendImageManually.setChecked(True)
        self.radioButton_sendImageManually.setObjectName("radioButton_sendImageManually")
        self.verticalLayout_9.addWidget(self.radioButton_sendImageManually)
        self.pbt_sendImage = QtWidgets.QPushButton(self.groupBox_9)
        self.pbt_sendImage.setObjectName("pbt_sendImage")
        self.verticalLayout_9.addWidget(self.pbt_sendImage)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(250, 10, 641, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_previewWindow = QtWidgets.QLabel(self.groupBox_7)
        self.label_previewWindow.setGeometry(QtCore.QRect(10, 20, 621, 341))
        self.label_previewWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.label_previewWindow.setText("")
        self.label_previewWindow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_previewWindow.setObjectName("label_previewWindow")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_4 = QtWidgets.QWidget(self.tab_3)
        self.widget_4.setGeometry(QtCore.QRect(10, 10, 231, 641))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbt_videoOpenFile = QtWidgets.QPushButton(self.groupBox_10)
        self.pbt_videoOpenFile.setObjectName("pbt_videoOpenFile")
        self.verticalLayout_6.addWidget(self.pbt_videoOpenFile)
        self.lineEdit_videoFileName = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_videoFileName.setObjectName("lineEdit_videoFileName")
        self.verticalLayout_6.addWidget(self.lineEdit_videoFileName)
        self.verticalLayout_7.addWidget(self.groupBox_10)
        self.groupBox_16 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_16.setObjectName("groupBox_16")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_16)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_16)
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_videoInfoFramerate = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_videoInfoFramerate.setObjectName("lineEdit_videoInfoFramerate")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_videoInfoFramerate)
        self.label_10 = QtWidgets.QLabel(self.groupBox_16)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_videoInfoDuration = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_videoInfoDuration.setObjectName("lineEdit_videoInfoDuration")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_videoInfoDuration)
        self.verticalLayout_7.addWidget(self.groupBox_16)
        self.groupBox_11 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.radioButton_videoPreviewRaw = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_videoPreviewRaw.setChecked(True)
        self.radioButton_videoPreviewRaw.setObjectName("radioButton_videoPreviewRaw")
        self.verticalLayout_10.addWidget(self.radioButton_videoPreviewRaw)
        self.radioButton_videoPreviewGray = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_videoPreviewGray.setObjectName("radioButton_videoPreviewGray")
        self.verticalLayout_10.addWidget(self.radioButton_videoPreviewGray)
        self.radioButton_videoPreviewBW = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_videoPreviewBW.setObjectName("radioButton_videoPreviewBW")
        self.verticalLayout_10.addWidget(self.radioButton_videoPreviewBW)
        self.verticalLayout_7.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_12)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_12)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBox_videoBWThreshold = QtWidgets.QSpinBox(self.groupBox_12)
        self.spinBox_videoBWThreshold.setMinimum(1)
        self.spinBox_videoBWThreshold.setMaximum(254)
        self.spinBox_videoBWThreshold.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_videoBWThreshold.setProperty("value", 127)
        self.spinBox_videoBWThreshold.setDisplayIntegerBase(10)
        self.spinBox_videoBWThreshold.setObjectName("spinBox_videoBWThreshold")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_videoBWThreshold)
        self.horizontalSlider_videoBWThreshold = QtWidgets.QSlider(self.groupBox_12)
        self.horizontalSlider_videoBWThreshold.setMinimum(1)
        self.horizontalSlider_videoBWThreshold.setMaximum(254)
        self.horizontalSlider_videoBWThreshold.setProperty("value", 127)
        self.horizontalSlider_videoBWThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_videoBWThreshold.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_videoBWThreshold.setTickInterval(10)
        self.horizontalSlider_videoBWThreshold.setObjectName("horizontalSlider_videoBWThreshold")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalSlider_videoBWThreshold)
        self.checkBox_videoBWInvert = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_videoBWInvert.setObjectName("checkBox_videoBWInvert")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_videoBWInvert)
        self.checkBox_videoPreviewBW2x = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_videoPreviewBW2x.setChecked(True)
        self.checkBox_videoPreviewBW2x.setObjectName("checkBox_videoPreviewBW2x")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_videoPreviewBW2x)
        self.verticalLayout_7.addWidget(self.groupBox_12)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(250, 10, 641, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_videoPreviewWindow = QtWidgets.QLabel(self.groupBox_13)
        self.label_videoPreviewWindow.setGeometry(QtCore.QRect(10, 20, 621, 311))
        self.label_videoPreviewWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.label_videoPreviewWindow.setText("")
        self.label_videoPreviewWindow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_videoPreviewWindow.setObjectName("label_videoPreviewWindow")
        self.horizontalSlider_videoPreviewFrameOffset = QtWidgets.QSlider(self.groupBox_13)
        self.horizontalSlider_videoPreviewFrameOffset.setEnabled(False)
        self.horizontalSlider_videoPreviewFrameOffset.setGeometry(QtCore.QRect(9, 340, 621, 22))
        self.horizontalSlider_videoPreviewFrameOffset.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_videoPreviewFrameOffset.setObjectName("horizontalSlider_videoPreviewFrameOffset")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(250, 390, 641, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setObjectName("groupBox_14")
        self.widget_7 = QtWidgets.QWidget(self.groupBox_14)
        self.widget_7.setGeometry(QtCore.QRect(10, 20, 371, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_videoPreviewOutputBW = QtWidgets.QLabel(self.widget_7)
        self.label_videoPreviewOutputBW.setFrameShape(QtWidgets.QFrame.Box)
        self.label_videoPreviewOutputBW.setText("")
        self.label_videoPreviewOutputBW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_videoPreviewOutputBW.setObjectName("label_videoPreviewOutputBW")
        self.gridLayout_2.addWidget(self.label_videoPreviewOutputBW, 0, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setGeometry(QtCore.QRect(390, 20, 241, 231))
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_15)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_15)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_videoSendFramerate = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_videoSendFramerate.setMinimum(1)
        self.spinBox_videoSendFramerate.setMaximum(60)
        self.spinBox_videoSendFramerate.setProperty("value", 24)
        self.spinBox_videoSendFramerate.setObjectName("spinBox_videoSendFramerate")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_videoSendFramerate)
        self.label_12 = QtWidgets.QLabel(self.groupBox_15)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox_videoFrameOffset = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBox_videoFrameOffset.setObjectName("spinBox_videoFrameOffset")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_videoFrameOffset)
        self.pbt_videoStartSending = QtWidgets.QPushButton(self.groupBox_15)
        self.pbt_videoStartSending.setObjectName("pbt_videoStartSending")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pbt_videoStartSending)
        self.textEdit_videoSendInfo = QtWidgets.QTextEdit(self.groupBox_15)
        self.textEdit_videoSendInfo.setObjectName("textEdit_videoSendInfo")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.textEdit_videoSendInfo)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_8 = QtWidgets.QWidget(self.tab_2)
        self.widget_8.setGeometry(QtCore.QRect(10, 10, 231, 641))
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_17 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pbt_screenSampleWindow = QtWidgets.QPushButton(self.groupBox_17)
        self.pbt_screenSampleWindow.setObjectName("pbt_screenSampleWindow")
        self.verticalLayout_12.addWidget(self.pbt_screenSampleWindow)
        self.checkBox_sampleWindowShowOnTop = QtWidgets.QCheckBox(self.groupBox_17)
        self.checkBox_sampleWindowShowOnTop.setChecked(True)
        self.checkBox_sampleWindowShowOnTop.setObjectName("checkBox_sampleWindowShowOnTop")
        self.verticalLayout_12.addWidget(self.checkBox_sampleWindowShowOnTop)
        self.verticalLayout_11.addWidget(self.groupBox_17)
        self.groupBox_19 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_screenPreviewRaw = QtWidgets.QRadioButton(self.groupBox_19)
        self.radioButton_screenPreviewRaw.setChecked(True)
        self.radioButton_screenPreviewRaw.setObjectName("radioButton_screenPreviewRaw")
        self.verticalLayout_13.addWidget(self.radioButton_screenPreviewRaw)
        self.radioButton_screenPreviewGray = QtWidgets.QRadioButton(self.groupBox_19)
        self.radioButton_screenPreviewGray.setObjectName("radioButton_screenPreviewGray")
        self.verticalLayout_13.addWidget(self.radioButton_screenPreviewGray)
        self.radioButton_screenPreviewBW = QtWidgets.QRadioButton(self.groupBox_19)
        self.radioButton_screenPreviewBW.setObjectName("radioButton_screenPreviewBW")
        self.verticalLayout_13.addWidget(self.radioButton_screenPreviewBW)
        self.verticalLayout_11.addWidget(self.groupBox_19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_20.setObjectName("groupBox_20")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_20)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_15 = QtWidgets.QLabel(self.groupBox_20)
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.spinBox_screenBWThreshold = QtWidgets.QSpinBox(self.groupBox_20)
        self.spinBox_screenBWThreshold.setMinimum(1)
        self.spinBox_screenBWThreshold.setMaximum(254)
        self.spinBox_screenBWThreshold.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.spinBox_screenBWThreshold.setProperty("value", 127)
        self.spinBox_screenBWThreshold.setDisplayIntegerBase(10)
        self.spinBox_screenBWThreshold.setObjectName("spinBox_screenBWThreshold")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_screenBWThreshold)
        self.horizontalSlider_screenBWThreshold = QtWidgets.QSlider(self.groupBox_20)
        self.horizontalSlider_screenBWThreshold.setMinimum(1)
        self.horizontalSlider_screenBWThreshold.setMaximum(254)
        self.horizontalSlider_screenBWThreshold.setProperty("value", 127)
        self.horizontalSlider_screenBWThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_screenBWThreshold.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_screenBWThreshold.setTickInterval(10)
        self.horizontalSlider_screenBWThreshold.setObjectName("horizontalSlider_screenBWThreshold")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalSlider_screenBWThreshold)
        self.checkBox_screenBWInvert = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_screenBWInvert.setObjectName("checkBox_screenBWInvert")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_screenBWInvert)
        self.checkBox_screenPreviewBW2x = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_screenPreviewBW2x.setChecked(True)
        self.checkBox_screenPreviewBW2x.setObjectName("checkBox_screenPreviewBW2x")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_screenPreviewBW2x)
        self.verticalLayout_11.addWidget(self.groupBox_20)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_21.setGeometry(QtCore.QRect(250, 10, 641, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_21.sizePolicy().hasHeightForWidth())
        self.groupBox_21.setSizePolicy(sizePolicy)
        self.groupBox_21.setObjectName("groupBox_21")
        self.label_screenPreviewWindow = QtWidgets.QLabel(self.groupBox_21)
        self.label_screenPreviewWindow.setGeometry(QtCore.QRect(10, 20, 621, 341))
        self.label_screenPreviewWindow.setFrameShape(QtWidgets.QFrame.Box)
        self.label_screenPreviewWindow.setText("")
        self.label_screenPreviewWindow.setAlignment(QtCore.Qt.AlignCenter)
        self.label_screenPreviewWindow.setObjectName("label_screenPreviewWindow")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_22.setGeometry(QtCore.QRect(250, 390, 641, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_22.sizePolicy().hasHeightForWidth())
        self.groupBox_22.setSizePolicy(sizePolicy)
        self.groupBox_22.setObjectName("groupBox_22")
        self.widget_9 = QtWidgets.QWidget(self.groupBox_22)
        self.widget_9.setGeometry(QtCore.QRect(10, 20, 371, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_screenPreviewOutputBW = QtWidgets.QLabel(self.widget_9)
        self.label_screenPreviewOutputBW.setFrameShape(QtWidgets.QFrame.Box)
        self.label_screenPreviewOutputBW.setText("")
        self.label_screenPreviewOutputBW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_screenPreviewOutputBW.setObjectName("label_screenPreviewOutputBW")
        self.gridLayout_3.addWidget(self.label_screenPreviewOutputBW, 0, 0, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_23.setGeometry(QtCore.QRect(390, 20, 241, 231))
        self.groupBox_23.setObjectName("groupBox_23")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_23)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_23)
        self.label_16.setObjectName("label_16")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBox_screenSendFramerate = QtWidgets.QSpinBox(self.groupBox_23)
        self.spinBox_screenSendFramerate.setMinimum(1)
        self.spinBox_screenSendFramerate.setMaximum(60)
        self.spinBox_screenSendFramerate.setProperty("value", 24)
        self.spinBox_screenSendFramerate.setObjectName("spinBox_screenSendFramerate")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_screenSendFramerate)
        self.pbt_screenStartSending = QtWidgets.QPushButton(self.groupBox_23)
        self.pbt_screenStartSending.setObjectName("pbt_screenStartSending")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.pbt_screenStartSending)
        self.textEdit_videoSendInfo_2 = QtWidgets.QTextEdit(self.groupBox_23)
        self.textEdit_videoSendInfo_2.setObjectName("textEdit_videoSendInfo_2")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.textEdit_videoSendInfo_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "OLED ToolBox"))
        self.groupBox.setTitle(_translate("mainWindow", "Serial Port Setting"))
        self.pbt_scanSerialPort.setText(_translate("mainWindow", "Scan Port"))
        self.label_8.setText(_translate("mainWindow", "Scan Port"))
        self.label_2.setText(_translate("mainWindow", "Baudrate"))
        self.pbt_serialOpen.setText(_translate("mainWindow", "Open"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Display Screen Setting"))
        self.label_3.setText(_translate("mainWindow", "Column"))
        self.label_4.setText(_translate("mainWindow", "Row"))
        self.label_5.setText(_translate("mainWindow", "Scan Direction"))
        self.comboBox_displayScanDirection.setItemText(0, _translate("mainWindow", "Horizontal"))
        self.comboBox_displayScanDirection.setItemText(1, _translate("mainWindow", "Vertical"))
        self.label_6.setText(_translate("mainWindow", "Byte Direction"))
        self.comboBox_displayByteDirection.setItemText(0, _translate("mainWindow", "Vertical"))
        self.comboBox_displayByteDirection.setItemText(1, _translate("mainWindow", "Horizontal"))
        self.label_13.setText(_translate("mainWindow", "Significan Bit"))
        self.comboBox_displaySignBit.setItemText(0, _translate("mainWindow", "LSB"))
        self.comboBox_displaySignBit.setItemText(1, _translate("mainWindow", "MSB"))
        self.label_14.setText(_translate("mainWindow", "Flip Mode"))
        self.checkBox_displayFlipH.setText(_translate("mainWindow", "Horizontal"))
        self.checkBox_displayFlipV.setText(_translate("mainWindow", "Vertical"))
        self.groupBox_18.setTitle(_translate("mainWindow", "Binarization"))
        self.radioButton_binarizationThreshold.setText(_translate("mainWindow", "Threshold"))
        self.radioButton_binarizationDither.setText(_translate("mainWindow", "Dither"))
        self.comboBox_ditherBayerSize.setItemText(0, _translate("mainWindow", "4M"))
        self.comboBox_ditherBayerSize.setItemText(1, _translate("mainWindow", "8M"))
        self.comboBox_ditherBayerSize.setItemText(2, _translate("mainWindow", "16M"))
        self.radioButton_binarizationErrorDiffusion.setText(_translate("mainWindow", "Error Diffusion"))
        self.checkBox_binarizationEqualizeHist.setText(_translate("mainWindow", "EqualizeHist"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Import Image"))
        self.pbt_openImageFile.setText(_translate("mainWindow", "Open Image"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Preview Selection"))
        self.radioButton_previewRaw.setText(_translate("mainWindow", "Raw"))
        self.radioButton_previewGray.setText(_translate("mainWindow", "Gray"))
        self.radioButton_previewBW.setText(_translate("mainWindow", "Black And White"))
        self.groupBox_5.setTitle(_translate("mainWindow", "Binarization"))
        self.label_7.setText(_translate("mainWindow", "BW Threshold"))
        self.checkBox_BWInvert.setText(_translate("mainWindow", "Invert BW"))
        self.checkBox_previewBW2x.setText(_translate("mainWindow", "Preview 2X"))
        self.groupBox_6.setTitle(_translate("mainWindow", "Export Setting"))
        self.radioButton_exportHexCArray.setText(_translate("mainWindow", "Hex C Array"))
        self.radioButton_exportHexValue.setText(_translate("mainWindow", "Hex Value"))
        self.pbt_exportImage.setText(_translate("mainWindow", "Export"))
        self.groupBox_8.setTitle(_translate("mainWindow", "Output BW Preview"))
        self.groupBox_9.setTitle(_translate("mainWindow", "Send to OLED"))
        self.radioButton_SendImageAuto.setText(_translate("mainWindow", "Auto"))
        self.radioButton_sendImageManually.setText(_translate("mainWindow", "Manually"))
        self.pbt_sendImage.setText(_translate("mainWindow", "Send One Frame"))
        self.groupBox_7.setTitle(_translate("mainWindow", "Preview Window"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Image"))
        self.groupBox_10.setTitle(_translate("mainWindow", "Video Import"))
        self.pbt_videoOpenFile.setText(_translate("mainWindow", "Open Video"))
        self.groupBox_16.setTitle(_translate("mainWindow", "Video Info"))
        self.label.setText(_translate("mainWindow", "FrameRate"))
        self.label_10.setText(_translate("mainWindow", "Duration"))
        self.groupBox_11.setTitle(_translate("mainWindow", "Preview Selection"))
        self.radioButton_videoPreviewRaw.setText(_translate("mainWindow", "Raw"))
        self.radioButton_videoPreviewGray.setText(_translate("mainWindow", "Gray"))
        self.radioButton_videoPreviewBW.setText(_translate("mainWindow", "Black And White"))
        self.groupBox_12.setTitle(_translate("mainWindow", "Binarization"))
        self.label_9.setText(_translate("mainWindow", "BW Threshold"))
        self.checkBox_videoBWInvert.setText(_translate("mainWindow", "Invert BW"))
        self.checkBox_videoPreviewBW2x.setText(_translate("mainWindow", "Preview 2X"))
        self.groupBox_13.setTitle(_translate("mainWindow", "Preview Window"))
        self.groupBox_14.setTitle(_translate("mainWindow", "Output BW Preview"))
        self.groupBox_15.setTitle(_translate("mainWindow", "Send Parameters Setting"))
        self.label_11.setText(_translate("mainWindow", "FrameRate"))
        self.label_12.setText(_translate("mainWindow", "FrameOffset"))
        self.pbt_videoStartSending.setText(_translate("mainWindow", "Start Sending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "Video"))
        self.groupBox_17.setTitle(_translate("mainWindow", "Screen Location"))
        self.pbt_screenSampleWindow.setText(_translate("mainWindow", "Open Sample Window"))
        self.checkBox_sampleWindowShowOnTop.setText(_translate("mainWindow", "Show on Top"))
        self.groupBox_19.setTitle(_translate("mainWindow", "Preview Selection"))
        self.radioButton_screenPreviewRaw.setText(_translate("mainWindow", "Raw"))
        self.radioButton_screenPreviewGray.setText(_translate("mainWindow", "Gray"))
        self.radioButton_screenPreviewBW.setText(_translate("mainWindow", "Black And White"))
        self.groupBox_20.setTitle(_translate("mainWindow", "Binarization"))
        self.label_15.setText(_translate("mainWindow", "BW Threshold"))
        self.checkBox_screenBWInvert.setText(_translate("mainWindow", "Invert BW"))
        self.checkBox_screenPreviewBW2x.setText(_translate("mainWindow", "Preview 2X"))
        self.groupBox_21.setTitle(_translate("mainWindow", "Preview Window"))
        self.groupBox_22.setTitle(_translate("mainWindow", "Output BW Preview"))
        self.groupBox_23.setTitle(_translate("mainWindow", "Send Parameters Setting"))
        self.label_16.setText(_translate("mainWindow", "FrameRate"))
        self.pbt_screenStartSending.setText(_translate("mainWindow", "Start Sending"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Screen"))
# import qt_images_rc
